### ISSUE TITLE
Creating interactive 3D maps with OpenStreetMap and Sketchfab

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/posts#4]
Frederik sent to cwg:
"people at "sketchfab.com" are very proud of their importing OSM data
into sketchfab as detailed here

<http://blog.sketchfab.com/post/107993471219/creating-interactive-3d-maps-with-openstreetmap>

and they would like us to increase their visibility by posting about
this on Facebook, Twitter, Blog, Featured Image, whatnot. They're
planning to build something where you can dirctly upload .osm files to them.

I said I'll forward their thing to CWG and whether or not you do
something with it, is entirely your choice."
Should we write about this?
Comment or close the issue.

**Comment by harry-wood** [comment]
We can't just suddenly out-of-the-blue have a blog post which is very promoting of one particular company with one particular 3D map visualisation approach. Maybe a tweet, but not a blog post. Because the there are many other 3D tools. We need to be treating them reasonably open-handedly.

It's an interesting topic area though. It comes up a lot with featured image proposals. It would be better to blog with a round up of "some of the latest developments in 3D visualising OSM data" which might mention sketchfab.  We could probably get some help from [Marek_kleciak](http://wiki.openstreetmap.org/wiki/User:Marek_kleciak) who seems to be very passionate on this topic (gave a talk at SOTM buenos aeries).

The other thing we can suggest to SketchFab is that they create themselves a wiki page (called "SketchFab") then I guess they can link that from the ['3D' wiki page](http://wiki.openstreetmap.org/wiki/3D)

**Comment by hbogner** [comment]
OK, so it's not for a blog post, more of a message in social network groups like I'm doing on G+?

**Comment by harry-wood** [comment]
very old idea which went nowhere
